Update metrics-template.md
chaoss/metrics pull request #190
Opened 2021-05-27 15:51 UTC by germonprez

Signed-off-by: Matt Germonprez <germonprez@gmail.com>

@klumb adding the disclaimer to the template

2021-06-02 03:12 UTC, GeorgLink requested changes
I suggest linking the issue number to the issue to make it easier for visitors to find the right issue and not have to guess which repository the issue is in.

2021-06-02 03:12 UTC, GeorgLink commented on resources/metrics-template.md
> +### This metric is a release candidate. To comment on this metric please see Issue #[put the respective Issue Number here]. Following a comment period, this metric will be included in the next regula
```suggestion
### This metric is a release candidate. To comment on this metric please see Issue [#[put the respective Issue Number here]](URL to issue). Following a comment period, this metric will be included in the next regular release.
```

2021-07-01 14:31 UTC, klumb commented
> I suggest linking the issue number to the issue to make it easier for visitors to find the right issue and not have to guess which repository the issue is in.

Yes, thank you georg

2021-07-01 14:31 UTC, klumb commented
this looks good I am going to merge this as we have other metrics template PRs coming

2021-07-01 22:12 UTC, GeorgLink commented
fixed merge conflict in browser -- breaks DCO sign-off -- manually overwriting and using squash merge.

2021-07-01 22:12 UTC, GeorgLink approved these changes

2021-07-01 22:13 UTC, merged